try {
    async_throw()
    "end try"
} catch {
    "ok"
}
